version: '3'

networks:
  turn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:

  coturn:
    image: coturn/coturn:4.5.2
    container_name: coturn
    restart: always
    user: root
    networks:
      turn_net:
        ipv4_address: 172.21.0.2
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "50000-50100:50000-50100/udp"
    volumes:
      - ./coturn/config/turnserver.conf:/etc/turnserver.conf
      - ./coturn/turndb:/var/lib/turn/turndb
      - ./coturn/log:/var/log
      - ./coturn/run:/var/run/coturn

  signaling:
    build: ./signaling-server
    container_name: signaling
    restart: unless-stopped
    networks:
      turn_net:
        ipv4_address: 172.21.0.3
    ports:
      - "8080:8080"
    volumes:
      - ./signaling-server/path/to:/app/path/to
    environment:
      - NODE_ENV=production
      - PORT=8080
      - SSL_KEY_PATH=./path/to/10.10.10.130-key.pem
      - SSL_CERT_PATH=./path/to/10.10.10.130.pem
